__title__ = 'Restcord'
__author__ = 'JustMaffie, Doezer'
__license__ = 'MIT'
__copyright__ = 'Copyright 2015-2018 JustMaffie, Doezer'
__github__ = "https://github.com/Doezer/Restcord"
__major__ = "1"
__minor__ = "1"
__patch__ = "0"
__version__ = "{}.{}.{}".format(__major__, __minor__, __patch__)
__credits__ = ["JustMaffie", "Doezer"]
__maintainer__ = "Doezer"
__status__ = "Development"
